name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps:set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps:set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Run brew test-bot --type=metadata
        run: brew test-bot --type=metadata

      - name: Run brew test-bot --type=formula
        run: brew test-bot --type=formula
